-- Seed Tabadul country_of_origin rows from Naqel's Tabadul CountryCode reference sheet.
--
-- Source: /Users/asma/Desktop/Customs AI/other/naqel-shared-data/Naqel
--         (Fields details + Mapping data).xlsx — sheet 'Tabadul CountryCode'.
--
-- Layout: source_value = ISO alpha-2 (INTLCODE column, e.g. 'CN', 'US', 'GB')
--         canonical_value = Tabadul numeric CountryCode (e.g. '142' for China)
--         metadata = { name_en, name_ar }
--
-- 307 rows. Same idempotent ON CONFLICT pattern as the currency seed (PR E).
--
-- This unblocks Phase 2 declaration rendering, which was failing on every
-- row whose country_of_origin wasn't yet seeded — most batches today fail
-- at this lookup step before XML can be written.

INSERT INTO tabadul_codes (code_type, source_value, canonical_value, metadata) VALUES
  ('country_of_origin', 'CW', '571', jsonb_build_object('name_en', 'CURACAO', 'name_ar', 'كوراكاو')),
  ('country_of_origin', 'ME', '573', jsonb_build_object('name_en', 'MONTENEQRO', 'name_ar', 'الجبل الأسود')),
  ('country_of_origin', 'SH', '256', jsonb_build_object('name_en', 'SAINT HELENA', 'name_ar', 'سانت هيلينا')),
  ('country_of_origin', 'KN', '460', jsonb_build_object('name_en', 'SAINT KITTS AND NEVIS', 'name_ar', 'سانت كيتس and نيفيس')),
  ('country_of_origin', 'LC', '447', jsonb_build_object('name_en', 'SAINT LUCIA', 'name_ar', 'سانت لوسيا')),
  ('country_of_origin', 'PM', '564', jsonb_build_object('name_en', 'SAINT PIERRE AND ', 'name_ar', 'سانت بيري and ميقويلون')),
  ('country_of_origin', 'VC', '451', jsonb_build_object('name_en', 'SAINT VINCENT', 'name_ar', 'سانت فينسنت')),
  ('country_of_origin', 'SV', '429', jsonb_build_object('name_en', 'SALVADOR', 'name_ar', 'سلفادور')),
  ('country_of_origin', 'WS', '312', jsonb_build_object('name_en', 'SAMOA', 'name_ar', 'ساموا')),
  ('country_of_origin', 'SM', '556', jsonb_build_object('name_en', 'SAN MARINO', 'name_ar', 'سان مارينو')),
  ('country_of_origin', 'ST', '268', jsonb_build_object('name_en', 'SAO TOME AND PRINCIPE', 'name_ar', 'ساو تومي and برينسيبي')),
  ('country_of_origin', 'SA', '100', jsonb_build_object('name_en', 'SAUDI ARABIA', 'name_ar', 'السعوديه')),
  ('country_of_origin', 'SN', '221', jsonb_build_object('name_en', 'SENEGAL', 'name_ar', 'السنيغال')),
  ('country_of_origin', 'CS', '550', jsonb_build_object('name_en', 'SERBIA AND MONTENGRO', 'name_ar', 'صربيا والجبل الاسود')),
  ('country_of_origin', 'SC', '261', jsonb_build_object('name_en', 'SEYCHELLES', 'name_ar', 'سيشلس')),
  ('country_of_origin', 'SL', '224', jsonb_build_object('name_en', 'SIERRA LEONE', 'name_ar', 'سيراليون')),
  ('country_of_origin', 'SG', '136', jsonb_build_object('name_en', 'SINGAPORE', 'name_ar', 'سنغافوره')),
  ('country_of_origin', 'SK', '553', jsonb_build_object('name_en', 'SLOVAKIA', 'name_ar', 'سلوفاكيا')),
  ('country_of_origin', 'SI', '547', jsonb_build_object('name_en', 'SLOVENIA', 'name_ar', 'سلوفانيا')),
  ('country_of_origin', 'SB', '317', jsonb_build_object('name_en', 'SOLOMON ISLANDS', 'name_ar', 'جزر سولومون')),
  ('country_of_origin', 'SO', '242', jsonb_build_object('name_en', 'SOMALIA', 'name_ar', 'الصومال')),
  ('country_of_origin', 'ZA', '254', jsonb_build_object('name_en', 'SOUTH AFRICA', 'name_ar', 'جنوب افريقيا')),
  ('country_of_origin', 'KR', '147', jsonb_build_object('name_en', 'SOUTH KOREA', 'name_ar', 'كوريا الجنوبية')),
  ('country_of_origin', 'ES', '526', jsonb_build_object('name_en', 'SPAIN', 'name_ar', 'إسبانيا')),
  ('country_of_origin', 'LK', '132', jsonb_build_object('name_en', 'SRI LANKA', 'name_ar', 'سريلانكا')),
  ('country_of_origin', 'SD', '215', jsonb_build_object('name_en', 'SUDAN', 'name_ar', 'السودان')),
  ('country_of_origin', 'SR', '423', jsonb_build_object('name_en', 'SURINAME', 'name_ar', 'سيرنام')),
  ('country_of_origin', 'SJ', '566', jsonb_build_object('name_en', 'SVALBARD AND JAN MAYEN', 'name_ar', 'سفالبارد and جان ماين')),
  ('country_of_origin', 'SZ', '253', jsonb_build_object('name_en', 'SWAZILAND', 'name_ar', 'سوازي لاند')),
  ('country_of_origin', 'SE', '511', jsonb_build_object('name_en', 'SWEDEN', 'name_ar', 'السويد')),
  ('country_of_origin', 'CH', '514', jsonb_build_object('name_en', 'SWITZERLAND', 'name_ar', 'سويسرا')),
  ('country_of_origin', 'SY', '110', jsonb_build_object('name_en', 'SYRIA ARAB REPUBLIC', 'name_ar', 'سوريا')),
  ('country_of_origin', 'TW', '143', jsonb_build_object('name_en', 'TAIWAN PROV.OF CHINA', 'name_ar', 'تايوان')),
  ('country_of_origin', 'TJ', '162', jsonb_build_object('name_en', 'TAJIKISTAN', 'name_ar', 'طاجكستان')),
  ('country_of_origin', 'TZ', '245', jsonb_build_object('name_en', 'TANZANIA,UN REPUBLIC', 'name_ar', 'تنزانيا')),
  ('country_of_origin', 'TH', '134', jsonb_build_object('name_en', 'THAILAND', 'name_ar', 'تايلاند')),
  ('country_of_origin', 'TL', '174', jsonb_build_object('name_en', 'TIMOR-LESTE', 'name_ar', 'تيمور ليستي')),
  ('country_of_origin', 'TG', '229', jsonb_build_object('name_en', 'TOGO', 'name_ar', 'توجو')),
  ('country_of_origin', 'TK', '329', jsonb_build_object('name_en', 'TOKELAU', 'name_ar', 'توكيلاو')),
  ('country_of_origin', 'TO', '330', jsonb_build_object('name_en', 'TONGA', 'name_ar', 'تونجا')),
  ('country_of_origin', 'TT', '419', jsonb_build_object('name_en', 'TRINIDAD AND TOBACO', 'name_ar', 'ترينيداد و توباكو')),
  ('country_of_origin', 'TN', '212', jsonb_build_object('name_en', 'TUNISIA', 'name_ar', 'تونس')),
  ('country_of_origin', 'TR', '525', jsonb_build_object('name_en', 'TURKEY', 'name_ar', 'تركيا')),
  ('country_of_origin', 'TM', '159', jsonb_build_object('name_en', 'TURKMENISTAN', 'name_ar', 'تركمانستان')),
  ('country_of_origin', 'TC', '567', jsonb_build_object('name_en', 'TURKS_CAICOS ISLANDS', 'name_ar', 'جزر توركس _ كايكوس')),
  ('country_of_origin', 'TV', '331', jsonb_build_object('name_en', 'TUVALU', 'name_ar', 'توفاليو')),
  ('country_of_origin', 'UG', '243', jsonb_build_object('name_en', 'UGANDA', 'name_ar', 'اوغندا')),
  ('country_of_origin', 'UA', '544', jsonb_build_object('name_en', 'UKRAINE', 'name_ar', 'اوكرانيا')),
  ('country_of_origin', 'AE', '120', jsonb_build_object('name_en', 'UNITED ARAB EMIRATE', 'name_ar', 'الإمارات')),
  ('country_of_origin', 'GB', '521', jsonb_build_object('name_en', 'UNITED KINGDOM', 'name_ar', 'المملكة المتحدة')),
  ('country_of_origin', 'US', '410', jsonb_build_object('name_en', 'UNITED STATES', 'name_ar', 'أمريكا')),
  ('country_of_origin', 'UY', '441', jsonb_build_object('name_en', 'URUGUAY', 'name_ar', 'أرجواي')),
  ('country_of_origin', 'UM', '461', jsonb_build_object('name_en', 'U.S.MINOR OUTLYING', 'name_ar', 'جزر أمريكا الثانوية')),
  ('country_of_origin', 'UZ', '158', jsonb_build_object('name_en', 'UZBEKISTAN', 'name_ar', 'أوزباكستان')),
  ('country_of_origin', 'VU', '450', jsonb_build_object('name_en', 'VANUATU', 'name_ar', 'فنواتو')),
  ('country_of_origin', 'VE', '434', jsonb_build_object('name_en', 'VENEZUELA', 'name_ar', 'فنزويلا')),
  ('country_of_origin', 'VN', '140', jsonb_build_object('name_en', 'VIET NAM', 'name_ar', 'فيتنام')),
  ('country_of_origin', 'VG', '462', jsonb_build_object('name_en', 'VIRGIN ISLANDS, U.K.', 'name_ar', 'جزر فيرجين البريطاني')),
  ('country_of_origin', 'WF', '332', jsonb_build_object('name_en', 'WALLIS AND FUTUNA', 'name_ar', 'واليس and فوتونا')),
  ('country_of_origin', 'EH', '269', jsonb_build_object('name_en', 'WESTERN SAHARA', 'name_ar', 'الصحراء الغربية')),
  ('country_of_origin', 'YE', '115', jsonb_build_object('name_en', 'YEMEN', 'name_ar', 'اليمن')),
  ('country_of_origin', 'ZM', '247', jsonb_build_object('name_en', 'ZAMBIA', 'name_ar', 'زامبيا')),
  ('country_of_origin', 'ZW', '249', jsonb_build_object('name_en', 'ZIMBABWE', 'name_ar', 'زيمبابوي')),
  ('country_of_origin', 'AL', '538', jsonb_build_object('name_en', 'ALBANIA', 'name_ar', 'ألبانيا')),
  ('country_of_origin', 'DZ', '211', jsonb_build_object('name_en', 'ALGERIA', 'name_ar', 'الجزائر')),
  ('country_of_origin', 'AD', '558', jsonb_build_object('name_en', 'ANDORRA', 'name_ar', 'أندورا')),
  ('country_of_origin', 'AO', '246', jsonb_build_object('name_en', 'ANGOLA', 'name_ar', 'أنجولا')),
  ('country_of_origin', 'AI', '464', jsonb_build_object('name_en', 'ANGUILLA', 'name_ar', 'أنجويلا')),
  ('country_of_origin', 'AQ', '175', jsonb_build_object('name_en', 'ANTARCTICA', 'name_ar', 'انتاركتيكا')),
  ('country_of_origin', 'AG', '416', jsonb_build_object('name_en', 'ANTIGUA AND BARBUDA', 'name_ar', 'أنتيقوا و باربودا')),
  ('country_of_origin', 'AR', '442', jsonb_build_object('name_en', 'ARGENTINA', 'name_ar', 'الأرجنتين')),
  ('country_of_origin', 'AM', '157', jsonb_build_object('name_en', 'ARMENIA', 'name_ar', 'أرمينيا')),
  ('country_of_origin', 'AW', '453', jsonb_build_object('name_en', 'ARUBA', 'name_ar', 'أروبا')),
  ('country_of_origin', 'AU', '310', jsonb_build_object('name_en', 'AUSTRALIA', 'name_ar', 'أستراليا')),
  ('country_of_origin', 'AT', '516', jsonb_build_object('name_en', 'AUSTRIA', 'name_ar', 'النمسا')),
  ('country_of_origin', 'AZ', '156', jsonb_build_object('name_en', 'AZERBAIJAN', 'name_ar', 'أذربيجان')),
  ('country_of_origin', 'BS', '414', jsonb_build_object('name_en', 'BAHAMAS', 'name_ar', 'بهاما')),
  ('country_of_origin', 'BH', '116', jsonb_build_object('name_en', 'BAHRAIN', 'name_ar', 'البحرين')),
  ('country_of_origin', 'BD', '130', jsonb_build_object('name_en', 'BANGLADESH', 'name_ar', 'بنغلادش')),
  ('country_of_origin', 'BB', '418', jsonb_build_object('name_en', 'BARBADOES', 'name_ar', 'بربدوس')),
  ('country_of_origin', 'BY', '166', jsonb_build_object('name_en', 'BELARUS', 'name_ar', 'بيلاروس')),
  ('country_of_origin', 'BE', '519', jsonb_build_object('name_en', 'BELGIUM', 'name_ar', 'بلجيكا')),
  ('country_of_origin', 'BZ', '448', jsonb_build_object('name_en', 'BELIZE', 'name_ar', 'بيليز')),
  ('country_of_origin', 'BJ', '230', jsonb_build_object('name_en', 'BENIN', 'name_ar', 'بنين')),
  ('country_of_origin', 'BM', '413', jsonb_build_object('name_en', 'BERMUDA', 'name_ar', 'برمودا')),
  ('country_of_origin', 'BT', '167', jsonb_build_object('name_en', 'BHUTAN', 'name_ar', 'بهوتان')),
  ('country_of_origin', 'BO', '438', jsonb_build_object('name_en', 'BOLIVIA', 'name_ar', 'بوليفيا')),
  ('country_of_origin', 'BA', '549', jsonb_build_object('name_en', 'BOSNIA_HERZEGOVINA', 'name_ar', 'البوسنة والهرسك')),
  ('country_of_origin', 'BW', '251', jsonb_build_object('name_en', 'BOTSWANA', 'name_ar', 'بوتسوانا')),
  ('country_of_origin', 'BV', '168', jsonb_build_object('name_en', 'BOUVET ISLAND', 'name_ar', 'جزيرة بوفيت')),
  ('country_of_origin', 'BR', '439', jsonb_build_object('name_en', 'BRAZIL', 'name_ar', 'البرازيل')),
  ('country_of_origin', 'IO', '169', jsonb_build_object('name_en', 'BRITISH INDIAN OCEAN', 'name_ar', 'بريتش انديان اوشن')),
  ('country_of_origin', 'BN', '151', jsonb_build_object('name_en', 'BRUNEI DARUSSALAM', 'name_ar', 'بروناي دار السلام')),
  ('country_of_origin', 'BG', '539', jsonb_build_object('name_en', 'BULGARIA', 'name_ar', 'بلغاريا')),
  ('country_of_origin', 'BF', '264', jsonb_build_object('name_en', 'BURKINA FASO', 'name_ar', 'بوركينا فاسو')),
  ('country_of_origin', 'BI', '239', jsonb_build_object('name_en', 'BURUNDI', 'name_ar', 'بوروندي')),
  ('country_of_origin', 'KH', '138', jsonb_build_object('name_en', 'CAMBODIA', 'name_ar', 'كامبوديا')),
  ('country_of_origin', 'CM', '232', jsonb_build_object('name_en', 'CAMEROON', 'name_ar', 'الكاميرون')),
  ('country_of_origin', 'CA', '411', jsonb_build_object('name_en', 'CANADA', 'name_ar', 'كندا')),
  ('country_of_origin', 'CV', '262', jsonb_build_object('name_en', 'CAPE VERDE ISLANDS', 'name_ar', 'جزر كيب فردي')),
  ('country_of_origin', 'KY', '449', jsonb_build_object('name_en', 'CAYMAN ISLANDS', 'name_ar', 'جزر الكيمان')),
  ('country_of_origin', 'CF', '233', jsonb_build_object('name_en', 'CENTRAL AFRICA REPUB', 'name_ar', 'جمهورية افريقيا وسطى')),
  ('country_of_origin', 'TD', '220', jsonb_build_object('name_en', 'CHAD', 'name_ar', 'تشاد')),
  ('country_of_origin', 'CL', '437', jsonb_build_object('name_en', 'CHILE', 'name_ar', 'تشيلي')),
  ('country_of_origin', 'CN', '142', jsonb_build_object('name_en', 'CHINA', 'name_ar', 'الصين الشعبية')),
  ('country_of_origin', 'CX', '170', jsonb_build_object('name_en', 'CHRISTMAS ISLAND', 'name_ar', 'جزيرة كريسماس')),
  ('country_of_origin', 'CC', '171', jsonb_build_object('name_en', 'COCOS ISLANDS', 'name_ar', 'جزر كوكوس (كيلينج)')),
  ('country_of_origin', 'CO', '433', jsonb_build_object('name_en', 'COLOMBIA', 'name_ar', 'كولومبيا')),
  ('country_of_origin', 'KM', '257', jsonb_build_object('name_en', 'COMOROS ISLANDS', 'name_ar', 'جزر القمر')),
  ('country_of_origin', 'CG', '235', jsonb_build_object('name_en', 'CONGO', 'name_ar', 'كونغو')),
  ('country_of_origin', 'CD', '265', jsonb_build_object('name_en', 'CONGO', 'name_ar', 'كونجو')),
  ('country_of_origin', 'CK', '333', jsonb_build_object('name_en', 'COOK ISLANDS', 'name_ar', 'جزر كوك')),
  ('country_of_origin', 'CR', '431', jsonb_build_object('name_en', 'COSTA RICA', 'name_ar', 'كوستاريكا')),
  ('country_of_origin', 'HR', '548', jsonb_build_object('name_en', 'CROATIA', 'name_ar', 'كرواتيا')),
  ('country_of_origin', 'CU', '425', jsonb_build_object('name_en', 'CUBA', 'name_ar', 'كوبا')),
  ('country_of_origin', 'CY', '531', jsonb_build_object('name_en', 'CYPRUS', 'name_ar', 'قبرص')),
  ('country_of_origin', 'CZ', '537', jsonb_build_object('name_en', 'CZECH REPUBLIC', 'name_ar', 'التشيك')),
  ('country_of_origin', 'DK', '513', jsonb_build_object('name_en', 'DENMARK', 'name_ar', 'الدنمارك')),
  ('country_of_origin', 'DJ', '241', jsonb_build_object('name_en', 'DJIBOUTI', 'name_ar', 'جيبوتي')),
  ('country_of_origin', 'DM', '417', jsonb_build_object('name_en', 'DOMINICA', 'name_ar', 'دومينكا')),
  ('country_of_origin', 'DO', '427', jsonb_build_object('name_en', 'DOMINICAN REPUBLIC', 'name_ar', 'جمهورية الدومينيكان')),
  ('country_of_origin', 'EC', '435', jsonb_build_object('name_en', 'ECUADOR', 'name_ar', 'أكوادور')),
  ('country_of_origin', 'EG', '214', jsonb_build_object('name_en', 'EGYPT', 'name_ar', 'مصر')),
  ('country_of_origin', 'GQ', '237', jsonb_build_object('name_en', 'EQUATORIAL GUINEA', 'name_ar', 'غينيا الاستوائية')),
  ('country_of_origin', 'ER', '263', jsonb_build_object('name_en', 'ERETRIA', 'name_ar', 'أريتريا')),
  ('country_of_origin', 'EE', '541', jsonb_build_object('name_en', 'ESTONIA', 'name_ar', 'استونيا')),
  ('country_of_origin', 'ET', '240', jsonb_build_object('name_en', 'ETHIOPIA', 'name_ar', 'اثيوبيا')),
  ('country_of_origin', 'FK', '560', jsonb_build_object('name_en', 'FALKLAND ISLANDS', 'name_ar', 'جزر فولكلاند')),
  ('country_of_origin', 'FO', '561', jsonb_build_object('name_en', 'FAROE ISLANDS', 'name_ar', 'جزر فاروي')),
  ('country_of_origin', 'FJ', '311', jsonb_build_object('name_en', 'FIJI', 'name_ar', 'فيجي')),
  ('country_of_origin', 'FI', '510', jsonb_build_object('name_en', 'FINLAND', 'name_ar', 'فنلندا')),
  ('country_of_origin', 'FR', '522', jsonb_build_object('name_en', 'FRANCE', 'name_ar', 'فرنسا')),
  ('country_of_origin', 'GF', '424', jsonb_build_object('name_en', 'FRENCH GUIANA', 'name_ar', 'غينيا الفرنسية')),
  ('country_of_origin', 'PF', '321', jsonb_build_object('name_en', 'FRENCH POLYNESIA', 'name_ar', 'بولينسيا الفرنسية')),
  ('country_of_origin', 'TF', '322', jsonb_build_object('name_en', 'FRENCH SOUTHERN', 'name_ar', 'مناطق فرنسا الشمالية')),
  ('country_of_origin', 'GA', '234', jsonb_build_object('name_en', 'GABON', 'name_ar', 'جابون')),
  ('country_of_origin', 'GM', '222', jsonb_build_object('name_en', 'GAMBIA', 'name_ar', 'جامبيا')),
  ('country_of_origin', 'GE', '160', jsonb_build_object('name_en', 'GEORGIA', 'name_ar', 'جورجيا')),
  ('country_of_origin', 'GS', '565', jsonb_build_object('name_en', 'GEORGIA AND ISL', 'name_ar', 'جزر جورجيا and ساندويش')),
  ('country_of_origin', 'DE', '517', jsonb_build_object('name_en', 'GERMANY', 'name_ar', 'المانيا')),
  ('country_of_origin', 'GH', '226', jsonb_build_object('name_en', 'GHANA', 'name_ar', 'غانا')),
  ('country_of_origin', 'GI', '529', jsonb_build_object('name_en', 'GIBRALTAR', 'name_ar', 'جبل طارق')),
  ('country_of_origin', 'GR', '524', jsonb_build_object('name_en', 'GREECE', 'name_ar', 'اليونان')),
  ('country_of_origin', 'GL', '562', jsonb_build_object('name_en', 'GREENLAND', 'name_ar', 'جرينلاند')),
  ('country_of_origin', 'GD', '454', jsonb_build_object('name_en', 'GRENADA', 'name_ar', 'جرينادا')),
  ('country_of_origin', 'GP', '455', jsonb_build_object('name_en', 'GUADELOUPE', 'name_ar', 'جواديلوبي')),
  ('country_of_origin', 'GU', '316', jsonb_build_object('name_en', 'GUAM', 'name_ar', 'جوام')),
  ('country_of_origin', 'GT', '428', jsonb_build_object('name_en', 'GUATEMALA', 'name_ar', 'جواتيمالا')),
  ('country_of_origin', 'GN', '223', jsonb_build_object('name_en', 'GUINEA', 'name_ar', 'غينيا')),
  ('country_of_origin', 'GW', '266', jsonb_build_object('name_en', 'GUINEA-BISSAU', 'name_ar', 'غينيا بيساو')),
  ('country_of_origin', 'GY', '422', jsonb_build_object('name_en', 'GUYANA', 'name_ar', 'غوانا')),
  ('country_of_origin', 'HT', '426', jsonb_build_object('name_en', 'HAITI', 'name_ar', 'هاييتي')),
  ('country_of_origin', 'HM', '323', jsonb_build_object('name_en', 'HEARD AND ISLAND', 'name_ar', 'جزر هيرد and ماكدونالد')),
  ('country_of_origin', 'VA', '563', jsonb_build_object('name_en', 'HOLY SEE', 'name_ar', 'هولي سي')),
  ('country_of_origin', 'HN', '421', jsonb_build_object('name_en', 'HONDURAS', 'name_ar', 'هوندوراس')),
  ('country_of_origin', 'HK', '145', jsonb_build_object('name_en', 'HONG KONG', 'name_ar', 'هونج كونج')),
  ('country_of_origin', 'HU', '535', jsonb_build_object('name_en', 'HUNGARY', 'name_ar', 'هنجاريا')),
  ('country_of_origin', 'IS', '528', jsonb_build_object('name_en', 'ICELAND', 'name_ar', 'أيسلندا')),
  ('country_of_origin', 'IN', '131', jsonb_build_object('name_en', 'INDIA', 'name_ar', 'الهند')),
  ('country_of_origin', 'ID', '152', jsonb_build_object('name_en', 'INDONESIA', 'name_ar', 'أندونيسيا')),
  ('country_of_origin', 'IR', '127', jsonb_build_object('name_en', 'IRAN', 'name_ar', 'إيران')),
  ('country_of_origin', 'IQ', '114', jsonb_build_object('name_en', 'IRAQ', 'name_ar', 'العراق')),
  ('country_of_origin', 'IE', '500', jsonb_build_object('name_en', 'IRELAND', 'name_ar', 'إيرلندا')),
  ('country_of_origin', 'IT', '523', jsonb_build_object('name_en', 'ITALY', 'name_ar', 'إيطاليا')),
  ('country_of_origin', 'CI', '227', jsonb_build_object('name_en', 'DIVORY COAST', 'name_ar', 'ساحل العاج(كوت ديفوا')),
  ('country_of_origin', 'JM', '415', jsonb_build_object('name_en', 'JAMAICA', 'name_ar', 'جامايكا')),
  ('country_of_origin', 'JP', '148', jsonb_build_object('name_en', 'JAPAN', 'name_ar', 'اليابان')),
  ('country_of_origin', 'JO', '112', jsonb_build_object('name_en', 'JORDAN', 'name_ar', 'الأردن')),
  ('country_of_origin', 'KZ', '164', jsonb_build_object('name_en', 'KAZAKHSTAN', 'name_ar', 'كازاخستان')),
  ('country_of_origin', 'KE', '244', jsonb_build_object('name_en', 'KENYA', 'name_ar', 'كينيا')),
  ('country_of_origin', 'KI', '324', jsonb_build_object('name_en', 'KIRIBATI', 'name_ar', 'كيريباتي')),
  ('country_of_origin', 'KW', '113', jsonb_build_object('name_en', 'KUWAIT', 'name_ar', 'الكويت')),
  ('country_of_origin', 'KG', '163', jsonb_build_object('name_en', 'KYRGYZSTAN', 'name_ar', 'قيرقيزيستان')),
  ('country_of_origin', 'LA', '137', jsonb_build_object('name_en', 'LAO', 'name_ar', 'لاو')),
  ('country_of_origin', 'LV', '542', jsonb_build_object('name_en', 'LATVIA', 'name_ar', 'لاتفيا')),
  ('country_of_origin', 'LB', '111', jsonb_build_object('name_en', 'LEBANON', 'name_ar', 'لبنان')),
  ('country_of_origin', 'LS', '252', jsonb_build_object('name_en', 'LESOTHO', 'name_ar', 'ليسوتو')),
  ('country_of_origin', 'LR', '225', jsonb_build_object('name_en', 'LIBERIA', 'name_ar', 'ليبريا')),
  ('country_of_origin', 'LY', '213', jsonb_build_object('name_en', 'LIBYAN ARAB JAMAHIRI', 'name_ar', 'ليبيا')),
  ('country_of_origin', 'LI', '557', jsonb_build_object('name_en', 'LIECHTENSTEIN', 'name_ar', 'ليختنشتاين')),
  ('country_of_origin', 'LT', '543', jsonb_build_object('name_en', 'LITHWANIA', 'name_ar', 'لتوانيا')),
  ('country_of_origin', 'LU', '520', jsonb_build_object('name_en', 'LUXEMBOURG', 'name_ar', 'لوكسمبورج')),
  ('country_of_origin', 'MO', '144', jsonb_build_object('name_en', 'MACAO', 'name_ar', 'ماكاو')),
  ('country_of_origin', 'MK', '554', jsonb_build_object('name_en', 'MACEDONIA', 'name_ar', 'مقدونيا')),
  ('country_of_origin', 'MG', '258', jsonb_build_object('name_en', 'MADAGASCAR', 'name_ar', 'مدغشقر')),
  ('country_of_origin', 'MW', '248', jsonb_build_object('name_en', 'MALAWI', 'name_ar', 'ملاوي')),
  ('country_of_origin', 'MY', '135', jsonb_build_object('name_en', 'MALAYSIA', 'name_ar', 'ماليزيا')),
  ('country_of_origin', 'MV', '155', jsonb_build_object('name_en', 'MALDIVES', 'name_ar', 'مالديف')),
  ('country_of_origin', 'ML', '218', jsonb_build_object('name_en', 'MALI', 'name_ar', 'مالي')),
  ('country_of_origin', 'MT', '530', jsonb_build_object('name_en', 'MALTA', 'name_ar', 'مالطة')),
  ('country_of_origin', 'MH', '452', jsonb_build_object('name_en', 'MARSHALL ISLAND', 'name_ar', 'جزر مارشال')),
  ('country_of_origin', 'MQ', '456', jsonb_build_object('name_en', 'MARTINIQUE', 'name_ar', 'مارتينيقوي')),
  ('country_of_origin', 'MR', '217', jsonb_build_object('name_en', 'MAURITANIA', 'name_ar', 'موريتانيا')),
  ('country_of_origin', 'MU', '259', jsonb_build_object('name_en', 'MAURITIUS', 'name_ar', 'موريشيوس')),
  ('country_of_origin', 'YT', '267', jsonb_build_object('name_en', 'MAYOTTE', 'name_ar', 'مايوتي')),
  ('country_of_origin', 'MX', '443', jsonb_build_object('name_en', 'MEXICO', 'name_ar', 'مكسيك')),
  ('country_of_origin', 'FM', '172', jsonb_build_object('name_en', 'MICRONESIA', 'name_ar', 'ميكرونيسيا')),
  ('country_of_origin', 'MD', '546', jsonb_build_object('name_en', 'MOLDOVA, REPUBLIC OF', 'name_ar', 'مولدافيا')),
  ('country_of_origin', 'MC', '555', jsonb_build_object('name_en', 'MONACO', 'name_ar', 'موناكو')),
  ('country_of_origin', 'MN', '141', jsonb_build_object('name_en', 'MONGOLIA', 'name_ar', 'منغوليا')),
  ('country_of_origin', 'MS', '457', jsonb_build_object('name_en', 'MONTSERRAT', 'name_ar', 'مونتسيرات')),
  ('country_of_origin', 'MA', '210', jsonb_build_object('name_en', 'MOROCCO', 'name_ar', 'المغرب')),
  ('country_of_origin', 'MZ', '250', jsonb_build_object('name_en', 'MOZAMBIQUE', 'name_ar', 'موزمبيق')),
  ('country_of_origin', 'MM', '133', jsonb_build_object('name_en', 'MYANMAR', 'name_ar', 'ماينامار')),
  ('country_of_origin', 'NA', '255', jsonb_build_object('name_en', 'NAMEBIA', 'name_ar', 'ناميبيا')),
  ('country_of_origin', 'NR', '325', jsonb_build_object('name_en', 'NAURU', 'name_ar', 'ناورو')),
  ('country_of_origin', 'NP', '154', jsonb_build_object('name_en', 'NEPAL', 'name_ar', 'نيبال')),
  ('country_of_origin', 'NL', '518', jsonb_build_object('name_en', 'NETHERLAND', 'name_ar', 'هولندا')),
  ('country_of_origin', 'AN', '458', jsonb_build_object('name_en', 'NETHERLANDS ANTILLES', 'name_ar', 'نيثرلاندز انتيليز')),
  ('country_of_origin', 'NC', '318', jsonb_build_object('name_en', 'NEW CALEDONIA', 'name_ar', 'كاليدونيا الجديدة')),
  ('country_of_origin', 'NZ', '313', jsonb_build_object('name_en', 'NEW ZEALAND', 'name_ar', 'نيوزيلاندا')),
  ('country_of_origin', 'NI', '430', jsonb_build_object('name_en', 'NICARAGUA', 'name_ar', 'نيكاراجوا')),
  ('country_of_origin', 'NE', '219', jsonb_build_object('name_en', 'NIGER', 'name_ar', 'النيجر')),
  ('country_of_origin', 'NG', '231', jsonb_build_object('name_en', 'NIGERIA', 'name_ar', 'نيجيريا')),
  ('country_of_origin', 'NU', '326', jsonb_build_object('name_en', 'NIUE', 'name_ar', 'نايوي')),
  ('country_of_origin', 'NF', '459', jsonb_build_object('name_en', 'NORFOLK ISLAND', 'name_ar', 'جزيرة نورفولك')),
  ('country_of_origin', 'KP', '146', jsonb_build_object('name_en', 'NORTH KOREA', 'name_ar', 'كوريا الشمالية')),
  ('country_of_origin', 'MP', '173', jsonb_build_object('name_en', 'NORTH MARIANA ISLAND', 'name_ar', 'جزر ماريانا الشمالية')),
  ('country_of_origin', 'NO', '512', jsonb_build_object('name_en', 'NORWAY', 'name_ar', 'النرويج')),
  ('country_of_origin', 'OM', '119', jsonb_build_object('name_en', 'OMAN', 'name_ar', 'عمان')),
  ('country_of_origin', 'PK', '129', jsonb_build_object('name_en', 'PAKISTAN', 'name_ar', 'باكستان')),
  ('country_of_origin', 'PW', '327', jsonb_build_object('name_en', 'PALAU', 'name_ar', 'بالاو')),
  ('country_of_origin', 'PS', '165', jsonb_build_object('name_en', 'PALESTINE', 'name_ar', 'فلسطين')),
  ('country_of_origin', 'PA', '432', jsonb_build_object('name_en', 'PANAMA', 'name_ar', 'بنما')),
  ('country_of_origin', 'PG', '320', jsonb_build_object('name_en', 'PAPUA NEW GUINEA', 'name_ar', 'بابوا(غينيا الجديدة)')),
  ('country_of_origin', 'PY', '440', jsonb_build_object('name_en', 'PARAGUAY', 'name_ar', 'براجواي')),
  ('country_of_origin', 'PE', '436', jsonb_build_object('name_en', 'PERU', 'name_ar', 'بيرو')),
  ('country_of_origin', 'PH', '150', jsonb_build_object('name_en', 'PHILIPPINES', 'name_ar', 'الفلبين')),
  ('country_of_origin', 'PN', '328', jsonb_build_object('name_en', 'PITCAIRN', 'name_ar', 'بيتكايرن')),
  ('country_of_origin', 'PL', '533', jsonb_build_object('name_en', 'POLAND', 'name_ar', 'بولندا (بولونيا)')),
  ('country_of_origin', 'PT', '515', jsonb_build_object('name_en', 'PORTUGAL', 'name_ar', 'البرتغال')),
  ('country_of_origin', 'PR', '412', jsonb_build_object('name_en', 'PUERTO RICO', 'name_ar', 'بورتوريكو')),
  ('country_of_origin', 'QA', '117', jsonb_build_object('name_en', 'QATAR', 'name_ar', 'قطر')),
  ('country_of_origin', 'RE', '260', jsonb_build_object('name_en', 'REUNION', 'name_ar', 'ريونيون')),
  ('country_of_origin', 'RO', '540', jsonb_build_object('name_en', 'ROMANIA', 'name_ar', 'رومانيا')),
  ('country_of_origin', 'RU', '551', jsonb_build_object('name_en', 'RUSSIAN', 'name_ar', 'روسيا')),
  ('country_of_origin', 'RW', '238', jsonb_build_object('name_en', 'RWANDA', 'name_ar', 'رواندا')),
  ('country_of_origin', 'AF', '128', jsonb_build_object('name_en', 'AFGHANISTAN', 'name_ar', 'أفغانستان')),
  ('country_of_origin', 'EU', '950', jsonb_build_object('name_en', 'EUROBIAN UNITED', 'name_ar', 'الإتحاد الأوربي')),
  ('country_of_origin', 'VI', '463', jsonb_build_object('name_en', 'VIRGIN ISLANDS, U.S.', 'name_ar', 'جزر فيرجيني الأمريكي')),
  ('country_of_origin', 'RS', '568', jsonb_build_object('name_en', 'SERBIA', 'name_ar', 'صربيا')),
  ('country_of_origin', 'AS', '569', jsonb_build_object('name_en', 'AMERICAN SAMOA', 'name_ar', 'ساموا الأمريكيه')),
  ('country_of_origin', 'JE', '572', jsonb_build_object('name_en', 'JERSEY', 'name_ar', 'جيرسي')),
  ('country_of_origin', 'NULL', '601', jsonb_build_object('name_en', 'NULL', 'name_ar', 'مقيم')),
  ('country_of_origin', 'NULL', '602', jsonb_build_object('name_en', 'NULL', 'name_ar', 'قبائل نازحة')),
  ('country_of_origin', 'NULL', '603', jsonb_build_object('name_en', 'NULL', 'name_ar', 'أفراد قبائل')),
  ('country_of_origin', 'NULL', '604', jsonb_build_object('name_en', 'NULL', 'name_ar', 'أجنبي بجواز سعودي')),
  ('country_of_origin', 'GG', '570', jsonb_build_object('name_en', 'GUERNSEY', 'name_ar', 'غوريسني')),
  ('country_of_origin', 'SS', '270', jsonb_build_object('name_en', 'NULL', 'name_ar', 'جنوب السودان')),
  ('country_of_origin', 'NULL', '990', jsonb_build_object('name_en', 'NULL', 'name_ar', 'مقيم-نازح-قبائل-غيره')),
  ('country_of_origin', 'IM', '559', jsonb_build_object('name_en', 'ISLE OF MAN', 'name_ar', 'أيسل أوف مان')),
  ('country_of_origin', 'SAKAP', '75', jsonb_build_object('name_en', 'none', 'name_ar', 'جمرك ميناء الملك عبد الله')),
  ('country_of_origin', 'SAJIZ', '64', jsonb_build_object('name_en', 'jazan airport', 'name_ar', 'مطار جازان')),
  ('country_of_origin', 'SAJBI', '45', jsonb_build_object('name_en', 'King Fahad Industrial Port - Jubail', 'name_ar', 'ميناء الملك فهد الصناعي بالجبيل')),
  ('country_of_origin', 'SAYBI', '19', jsonb_build_object('name_en', 'King Fahad Industrial Port - Yanbu', 'name_ar', 'ميناء الملك فهد الصناعي بينبع')),
  ('country_of_origin', 'SAJED', '80', jsonb_build_object('name_en', 'MUNICIPALITY OF WESTERN REGION CUSTOMS', 'name_ar', 'أمانة جمارك الغربية')),
  ('country_of_origin', 'SADAM', '81', jsonb_build_object('name_en', 'MUNICIPALITY OF EASTERN REGION CUSTOMS', 'name_ar', 'أمانة جمارك الشرقية')),
  ('country_of_origin', 'SASOT', '82', jsonb_build_object('name_en', 'MUNICIPALITY OF SOUTHERN REGION CUSTOMS', 'name_ar', 'أمانة جمارك الجنوبية')),
  ('country_of_origin', 'SADAM', '83', jsonb_build_object('name_en', 'KING FAHAD BRIDGE CUSTOMS', 'name_ar', 'جمرك جسر الملك فهد')),
  ('country_of_origin', 'SAFRS', '84', jsonb_build_object('name_en', 'FARASAN CUSTOMS', 'name_ar', 'جمرك فرسان')),
  ('country_of_origin', 'SARAE', '90', jsonb_build_object('name_en', 'JADEEDAT ARA''AR CUSTOMS', 'name_ar', 'جمرك جديدة عرعر')),
  ('country_of_origin', 'SATRF', '91', jsonb_build_object('name_en', 'TRAIFF CUSTOMS', 'name_ar', 'جمرك طريف')),
  ('country_of_origin', 'SAAJF', '94', jsonb_build_object('name_en', 'none', 'name_ar', 'جمرك مطار الجوف')),
  ('country_of_origin', 'SAHDH', '95', jsonb_build_object('name_en', 'AL HADEETHAH CUSTOMS', 'name_ar', 'جمرك الحديثة')),
  ('country_of_origin', 'SARBG', '96', jsonb_build_object('name_en', 'RABIGH PORT CUSTOMS', 'name_ar', 'جمرك ميناء رابغ')),
  ('country_of_origin', 'SARUH', '99', jsonb_build_object('name_en', 'CUSTOMS MAIN OFFICE', 'name_ar', 'المكتب الرئيسي لمصلحة الجمارك')),
  ('country_of_origin', 'SAJED', '10', jsonb_build_object('name_en', 'JEDDAH ISLAMIC PORT CUSTOMS', 'name_ar', 'جمرك ميناء جده الاسلامي')),
  ('country_of_origin', 'SAJUB12', '101', jsonb_build_object('name_en', 'Jubail  Industrial Customs', 'name_ar', 'جمرك ميناء الجبيل الصناعي')),
  ('country_of_origin', 'SAAKH', '14', jsonb_build_object('name_en', 'PRINCE SULTAN AIR BASE CUSTOMS', 'name_ar', 'جمرك قاعدة الأمير سلطان الجوية')),
  ('country_of_origin', 'SAYNB', '17', jsonb_build_object('name_en', 'YANBU SEA PORT', 'name_ar', 'جمرك ميناء ينبع')),
  ('country_of_origin', 'SADMM', '20', jsonb_build_object('name_en', 'KING FAHAD INTERNATIONAL AIRPORT CUSTOMS', 'name_ar', 'جمرك مطار الملك فهد الدولي')),
  ('country_of_origin', 'SAMED', '21', jsonb_build_object('name_en', 'PRINCE MOHAMMED BIN ABDULAZIZ AIRPORT', 'name_ar', 'مطار الأمير محمد بن عبدالعزيز')),
  ('country_of_origin', 'SAELQ', '22', jsonb_build_object('name_en', 'QASIM AIRPORT CUSTOMS', 'name_ar', 'جمرك مطار القصيم')),
  ('country_of_origin', 'SARUH', '23', jsonb_build_object('name_en', 'KING KHALED INTERNATIONAL AIRPORT CUSTOMS ', 'name_ar', 'جمرك مطار الملك خالد الدولي')),
  ('country_of_origin', 'SATIF', '24', jsonb_build_object('name_en', 'TAIF AIRPORT CUSTOMS', 'name_ar', 'جمرك مطار الطائف')),
  ('country_of_origin', 'SAJED', '26', jsonb_build_object('name_en', 'none', 'name_ar', 'جمرك مطارالملك عبدالعزيز(بريد جدة)')),
  ('country_of_origin', 'SAMED', '27', jsonb_build_object('name_en', 'POSTAL PACKAGES CUSTOMS IN MADINAH', 'name_ar', 'جمرك الطرود البريدية بالمدينة')),
  ('country_of_origin', 'SARUH', '28', jsonb_build_object('name_en', 'none', 'name_ar', 'جمرك مطار الملك خالد(بريد الرياض)')),
  ('country_of_origin', 'SADAM', '30', jsonb_build_object('name_en', 'KING ABDULAIZ PORT CUSTOMS', 'name_ar', 'جمرك ميناء الملك عبدالعزيز')),
  ('country_of_origin', 'SABAT', '31', jsonb_build_object('name_en', 'BATEHA''A CUSTOMS', 'name_ar', 'جمرك البطحاء')),
  ('country_of_origin', 'SARTA', '32', jsonb_build_object('name_en', 'RAS TANOURA PORT', 'name_ar', 'جمرك ميناء رأس تنوره')),
  ('country_of_origin', 'SARUH', '34', jsonb_build_object('name_en', 'RIYADH DRY PORT CUSTOMS', 'name_ar', 'جمرك الميناء الجاف بالرياض')),
  ('country_of_origin', 'SARAQ', '35', jsonb_build_object('name_en', 'AL-ROQA''I CUSTOMS', 'name_ar', 'جمرك الرقعي')),
  ('country_of_origin', 'SAADD', '36', jsonb_build_object('name_en', 'AL-ODAID CUSTOMS', 'name_ar', 'جمرك العديد')),
  ('country_of_origin', 'SADMM', '38', jsonb_build_object('name_en', 'none', 'name_ar', 'جمرك مطارالملك فهد(البريد الممتاز)')),
  ('country_of_origin', 'SASAL', '41', jsonb_build_object('name_en', 'SALWA CUSTOMS', 'name_ar', 'جمرك سلوى')),
  ('country_of_origin', 'SAJUB', '42', jsonb_build_object('name_en', 'JUBAIL SEA PORT', 'name_ar', 'جمرك ميناء الجبيل')),
  ('country_of_origin', 'SARMS', '43', jsonb_build_object('name_en', 'RAS MISHA''AB CUSTOMS', 'name_ar', 'جمرك راس مشعاب')),
  ('country_of_origin', 'SAKAF', '44', jsonb_build_object('name_en', 'AL KHAFJI CUSTOMS', 'name_ar', 'جمرك الخفجي')),
  ('country_of_origin', 'SAMAK', '46', jsonb_build_object('name_en', 'none', 'name_ar', 'جمرك مطارالملك عبدالعزيز(بريد مكة)')),
  ('country_of_origin', 'SATUU', '50', jsonb_build_object('name_en', 'TABOUK AIRPORT CUSTOMS', 'name_ar', 'جمرك مطار تبوك')),
  ('country_of_origin', 'SAHAM', '51', jsonb_build_object('name_en', 'HALAT AMMAR CUSTOMS', 'name_ar', 'جمرك حالة عمار')),
  ('country_of_origin', 'SADHU', '53', jsonb_build_object('name_en', 'DHIBA PORT CUSTOMS', 'name_ar', 'جمرك ميناء ضباء')),
  ('country_of_origin', 'SADOR', '54', jsonb_build_object('name_en', 'AL DORRAH CUSTOMS', 'name_ar', 'جمرك الدره')),
  ('country_of_origin', 'SAJIZ', '60', jsonb_build_object('name_en', 'JIZAN PORT CUSTOMS', 'name_ar', 'جمرك ميناء جيزان')),
  ('country_of_origin', 'SATWL', '61', jsonb_build_object('name_en', 'AL TOUWAL CUSTOMS', 'name_ar', 'جمرك الطوال')),
  ('country_of_origin', 'SAMAU', '62', jsonb_build_object('name_en', 'AL MAWSIM CUSTOMS', 'name_ar', 'جمرك الموسم')),
  ('country_of_origin', 'SAKHO', '63', jsonb_build_object('name_en', 'AL KHOBAH CUSTOMS', 'name_ar', 'جمرك الخوبة')),
  ('country_of_origin', 'SAWAD', '66', jsonb_build_object('name_en', 'AL WADIEAH CUSTOMS', 'name_ar', 'جمرك الوديعة')),
  ('country_of_origin', 'SAALB', '67', jsonb_build_object('name_en', 'ALAB CUSTOMS', 'name_ar', 'جمرك علب')),
  ('country_of_origin', 'SAKHD', '69', jsonb_build_object('name_en', 'AL KHADRA CUSTOMS', 'name_ar', 'جمرك الخضراء')),
  ('country_of_origin', 'SAAHB', '71', jsonb_build_object('name_en', 'ABHA AIRPORT CUSTOMS', 'name_ar', 'جمرك مطار أبها')),
  ('country_of_origin', 'SASHW', '72', jsonb_build_object('name_en', 'SHARORAH AIRPORT CUSTOMS', 'name_ar', 'جمرك مطار شروره')),
  ('country_of_origin', 'SAJED', '11', jsonb_build_object('name_en', 'KING ABDULAZIZ INTERNATIONAL AIRPORT CUSTOM', 'name_ar', 'جمرك مطار الملك عبدالعزيز')),
  ('country_of_origin', 'SAJUB11', '102', jsonb_build_object('name_en', 'Jubail Commercial Customs', 'name_ar', 'جمرك ميناء الجبيل التجاري')),
  ('country_of_origin', 'SARKH', '33', jsonb_build_object('name_en', 'Ras alKHair Sea Port', 'name_ar', 'جمرك رأس الخير')),
  ('country_of_origin', 'SAYNB', '18', jsonb_build_object('name_en', 'YANBU AIR PORT', 'name_ar', 'جمرك مطار ينبع'));
ON CONFLICT ON CONSTRAINT tabadul_codes_natural_uniq DO NOTHING;
